### ISSUE TITLE
Unable to compile requestHandlers.js

### ISSUE THREAD

**Issue by Vagic** [manuelkiessling/nodebeginner.org#56]
Receive below error when compling with NodeJs version 0.10.35 (downloaded from http://nodejs.org/download/)

C:\A Work\Study\NodeJs\Code>node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'formidable'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\A Work\Study\NodeJs\Code\requestHandlers.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

C:\A Work\Study\NodeJs\Code>

**Comment by worgock** [comment]
You need to run "npm install formidable" from the project folder.

**Comment by manuelkiessling** [comment]
Thanks @worgock for supporting @Vagic!
