### ISSUE TITLE
undefined is not a function at route(pathname)

### ISSUE THREAD

**Issue by jeroldhaas** [manuelkiessling/nodebeginner.org#63]
From router beginning example:

index.js
```javascript
var server = require("./server");
var router = require("./router");

server.start()
```

server.js
```javascript
var http = require("http");
var url  = require("url");

function start(route) {
    function onRequest(request, response) {
        var pathname = url.parse(request.url).pathname;
        console.log("Request for " + pathname + " recieved.");

        route(pathname);

        response.writeHead(200, {
            "Content-Type": "text/plain"
        });
        response.write("Hello, world!");
        response.end();
    }

    http.createServer(onRequest).listen(8888);
    console.log("Server has started.");
}

exports.start = start;
```

router.js
```javascript
function route(pathname) {
    console.log("Abount to route a request for " + pathname);
}

exports.route = route;
```
Error output:
```log
c:\Projects\Personal\Node\learning-gulp\server.js:10
        route(pathname);
        ^
TypeError: undefined is not a function
    at Server.onRequest (c:\Projects\Personal\Node\learning-gulp\server.js:10:9)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by jeroldhaas** [comment]
Close: Missed `server.start(router.route);` to my chagrin. :blush:
